{% set version = "0.3.4" %}
{% set name = "pycoMeth" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv "
  entry_points:
    - pycoMeth=pycoMeth.__main__:main
  noarch: "python"

requirements:
  build:
    - python>=3.6
    - pip>=19.2.1
    - ripgrep>=11.0.1
  run:
    - numpy>=1.14.0
    - tqdm>=4.23.4
    - pandas>=0.25.1
    - statsmodels>=0.10.1
    - scipy>=1.3.1
    - pyfaidx>=0.5.5.2

test:
  imports:
    - pycoMeth.FileParser
    - pycoMeth.CoordGen
    - pycoMeth.CpG_Aggregate
    - pycoMeth.Interval_Aggregate
    - pycoMeth.Meth_Comp
    - pycoMeth.CGI_Finder
  commands:
    - pycoMeth CpG_Aggregate --help
    - pycoMeth Interval_Aggregate --help
    - pycoMeth Meth_Comp --help
    - pycoMeth CGI_Finder --help

about:
  home: "https://github.com/a-slide/pycoMeth"
  license: "MIT"
  summary: "DNA methylation analysis downstream to Nanopolish for Oxford Nanopore DNA sequencing datasets"
